### ISSUE TITLE
对 ftrl_model.h 实现细节有点疑问

### ISSUE THREAD

**Issue by littlejin** [CastellanZhang/alphaPLM#2]
作者您好，

在文件 ftrl_model.h 里，

第270行 uTx[f] -= max_uTx 这一步的意义是什么？

因为在第271行 uTx[f] = exp(uTx[f])，既然271行对uTx[f] 直接赋值了，为什么270还要对uTx[f]  做 -= 操作？

**Comment by CastellanZhang** [comment]
没看懂你想问什么？这两行：
        uTx[f] -= max_uTx;
        uTx[f] = exp(uTx[f]);
等价于下面这一行：
        uTx[f] = exp(uTx[f] - max_uTx);
只是我分成了两行而已。

**Comment by littlejin** [comment]
作者您好，

其实我没太理解，为什么要 uTx[f] - max_uTx

**Comment by CastellanZhang** [comment]
防止数值计算溢出。uTx[f]有时可能是个较大的正数，直接算exp(uTx[f])会超出double的范围导致算术溢出。而我们这里最终也不是要exp(uTx[f])的结果，而是一个比值：exp(uTx[f])/sum_j(exp(uTx[j]))，所以可以分子分母同时除以exp(max_uTx)。仔细看一下http://castellanzhang.github.io/2017/06/01/mlr_plm/ 的公式就明白了。

**Comment by littlejin** [comment]
好的，谢谢！
